# Generated by Django 5.2.6 on 2025-09-24 21:03

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('shop', '0002_remove_product_color_remove_product_size_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='product',
            name='sizes',
            field=models.JSONField(blank=True, default=list, help_text='List of sizes, e.g. ["S","M","L"]'),
        ),
    ]
