# Generated by Django 5.2.6 on 2025-09-24 21:08

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('shop', '0003_alter_product_sizes'),
    ]

    operations = [
        migrations.AlterField(
            model_name='product',
            name='colors',
            field=models.JSONField(blank=True, default=list, help_text='List of colors, e.g. ["Black","Red"]'),
        ),
    ]
