# Generated by Django 5.2.6 on 2025-09-24 21:16

from decimal import Decimal
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('shop', '0004_alter_product_colors'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='product',
            name='colors',
        ),
        migrations.AddField(
            model_name='product',
            name='reference_price',
            field=models.DecimalField(decimal_places=2, default=Decimal('0.00'), help_text='Price (in dollars) for the reference size', max_digits=8),
        ),
        migrations.AddField(
            model_name='product',
            name='reference_size',
            field=models.CharField(choices=[('XS', 'XS'), ('S', 'S'), ('M', 'M'), ('L', 'L'), ('XL', 'XL'), ('XXL', 'XXL'), ('XXXL', 'XXXL')], default='XS', help_text='Reference size used to calculate other sizes', max_length=5),
        ),
        migrations.AddField(
            model_name='product',
            name='size_prices',
            field=models.JSONField(blank=True, default=dict, help_text='Auto-generated mapping of size -> price (strings)'),
        ),
        migrations.AlterField(
            model_name='product',
            name='price',
            field=models.DecimalField(decimal_places=2, default=Decimal('0.00'), max_digits=8),
        ),
    ]
