# Generated by Django 5.2.6 on 2025-09-24 21:17

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('shop', '0005_remove_product_colors_product_reference_price_and_more'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='product',
            name='reference_price',
        ),
        migrations.RemoveField(
            model_name='product',
            name='reference_size',
        ),
        migrations.RemoveField(
            model_name='product',
            name='size_prices',
        ),
        migrations.AddField(
            model_name='product',
            name='colors',
            field=models.JSONField(blank=True, default=list, help_text='List of colors, e.g. ["Black","Red"]'),
        ),
        migrations.AlterField(
            model_name='product',
            name='price',
            field=models.DecimalField(decimal_places=2, max_digits=8),
        ),
    ]
