# Generated by Django 5.2.6 on 2025-09-29 23:15

import shop.models
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('shop', '0006_remove_product_reference_price_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='product',
            name='sizes',
            field=models.JSONField(blank=True, default=shop.models.default_sizes, help_text='List of sizes, e.g. ["S","M","L"]'),
        ),
    ]
