# Generated by Django 5.2.6 on 2025-10-03 01:29

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('shop', '0010_customerorder'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='orderitem',
            name='order',
        ),
        migrations.RemoveField(
            model_name='orderitem',
            name='product',
        ),
        migrations.DeleteModel(
            name='Order',
        ),
        migrations.DeleteModel(
            name='OrderItem',
        ),
    ]
