# Generated by Django 5.2.6 on 2025-10-03 02:20

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('shop', '0011_remove_orderitem_order_remove_orderitem_product_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='customerorder',
            name='customer_id',
            field=models.IntegerField(blank=True, help_text="Customer ID stored in session (request.session['customer_id'])", null=True),
        ),
    ]
