# Generated by Django 5.2.6 on 2025-10-04 23:27

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('shop', '0012_customerorder_customer_id'),
    ]

    operations = [
        migrations.AddField(
            model_name='product',
            name='Collection',
            field=models.JSONField(blank=True, default=list),
        ),
    ]
