# Generated by Django 5.2.6 on 2025-10-04 23:31

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('shop', '0013_product_collection'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='product',
            name='Collection',
        ),
    ]
