# Generated by Django 5.2.6 on 2025-10-05 00:49

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('shop', '0016_alter_product_collection_cat'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='product',
            name='collection_cat',
        ),
    ]
