# Generated by Django 5.2.6 on 2025-10-05 00:50

import multiselectfield.db.fields
from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('shop', '0017_remove_product_collection_cat'),
    ]

    operations = [
        migrations.AddField(
            model_name='product',
            name='collection_cat',
            field=multiselectfield.db.fields.MultiSelectField(blank=True, choices=[('Best_selling', 'Best Selling'), ('Trending', 'Trending'), ('Sale', 'Sale')], help_text='Select collection categories', max_length=50),
        ),
    ]
