# Generated by Django 5.2.6 on 2025-10-05 23:46

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('shop', '0019_cosmetic'),
    ]

    operations = [
        migrations.DeleteModel(
            name='Cosmetic',
        ),
    ]
