# Generated by Django 5.2.6 on 2025-10-05 23:47

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('shop', '0020_delete_cosmetic'),
    ]

    operations = [
        migrations.CreateModel(
            name='Cosmetic',
            fields=[
                ('cosmetic_product_id', models.AutoField(primary_key=True, serialize=False)),
                ('name', models.CharField(max_length=200)),
                ('price', models.DecimalField(decimal_places=2, max_digits=8)),
                ('image', models.ImageField(blank=True, null=True, upload_to='cosmetics/')),
                ('image_hover', models.ImageField(blank=True, null=True, upload_to='cosmetics/hover/')),
                ('created', models.DateTimeField(auto_now_add=True)),
                ('updated', models.DateTimeField(auto_now=True)),
            ],
            options={
                'verbose_name': 'Cosmetic',
                'verbose_name_plural': 'Cosmetics',
                'ordering': ['-created'],
            },
        ),
    ]
