# Generated by Django 5.2.6 on 2025-10-06 00:51

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('shop', '0021_cosmetic'),
    ]

    operations = [
        migrations.DeleteModel(
            name='Cosmetic',
        ),
    ]
