# Generated by Django 5.2.6 on 2025-10-06 00:52

import multiselectfield.db.fields
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('shop', '0022_delete_cosmetic'),
    ]

    operations = [
        migrations.CreateModel(
            name='Cosmetic',
            fields=[
                ('cosmetic_product_id', models.AutoField(primary_key=True, serialize=False)),
                ('name', models.CharField(max_length=200)),
                ('price', models.DecimalField(decimal_places=2, max_digits=8)),
                ('image', models.ImageField(blank=True, null=True, upload_to='cosmetics/')),
                ('image_hover', models.ImageField(blank=True, null=True, upload_to='cosmetics/hover/')),
                ('short_desc', models.CharField(blank=True, help_text='Short description of the product', max_length=255)),
                ('collection', multiselectfield.db.fields.MultiSelectField(blank=True, choices=[('Best_selling', 'Best Selling'), ('Trending', 'Trending'), ('Sale', 'Sale')], help_text='Select one or more collection categories', max_length=50)),
                ('brand', models.CharField(choices=[("L'Oréal Paris", "L'Oréal Paris"), ('Maybelline', 'Maybelline'), ('MAC', 'MAC'), ('Huda Beauty', 'Huda Beauty'), ('Fenty Beauty', 'Fenty Beauty')], default="L'Oréal Paris", max_length=50)),
            ],
        ),
    ]
