# Generated by Django 5.2.6 on 2025-10-06 01:01

import multiselectfield.db.fields
from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('shop', '0023_cosmetic'),
    ]

    operations = [
        migrations.AlterField(
            model_name='cosmetic',
            name='collection',
            field=multiselectfield.db.fields.MultiSelectField(blank=True, choices=[('We_recommed', 'We_recommed'), ('Whats_new', 'Whats_new'), ('Best_offer', 'Best_offer')], help_text='Select one or more collection categories', max_length=50),
        ),
    ]
