# Generated by Django 5.2.6 on 2025-10-06 01:05

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('shop', '0024_alter_cosmetic_collection'),
    ]

    operations = [
        migrations.AlterField(
            model_name='cosmetic',
            name='short_desc',
            field=models.TextField(blank=True, help_text='Short description of the product'),
        ),
    ]
