# Generated by Django 5.2.6 on 2025-10-07 23:21

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('shop', '0025_alter_cosmetic_short_desc'),
    ]

    operations = [
        migrations.CreateModel(
            name='Jewellery',
            fields=[
                ('jewellery_product_id', models.AutoField(primary_key=True, serialize=False)),
                ('name', models.CharField(max_length=200)),
                ('price', models.DecimalField(decimal_places=2, max_digits=8)),
                ('image', models.ImageField(blank=True, null=True, upload_to='jewellery/')),
                ('image_hover', models.ImageField(blank=True, null=True, upload_to='jewellery/hover/')),
                ('short_desc', models.TextField(blank=True, help_text='Short description of the product')),
            ],
        ),
    ]
