# Generated by Django 5.2.6 on 2025-10-08 01:12

import multiselectfield.db.fields
from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('shop', '0026_jewellery'),
    ]

    operations = [
        migrations.AddField(
            model_name='jewellery',
            name='collection',
            field=multiselectfield.db.fields.MultiSelectField(blank=True, choices=[('Most_selling', 'Most Selling'), ('Trending', 'Trending'), ('Sale', 'Sale')], help_text='Select one or more collection categories', max_length=50),
        ),
    ]
