# Generated by Django 5.2.6 on 2025-10-08 01:50

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('shop', '0027_jewellery_collection'),
    ]

    operations = [
        migrations.CreateModel(
            name='Bag',
            fields=[
                ('bag_product_id', models.AutoField(primary_key=True, serialize=False)),
                ('name', models.CharField(max_length=255)),
                ('price', models.DecimalField(decimal_places=2, max_digits=10)),
                ('collection', models.CharField(blank=True, choices=[('Most_Selling', 'Most Selling'), ('Trending', 'Trending'), ('Sale', 'Sale')], max_length=50, null=True)),
                ('desc', models.TextField(blank=True, null=True)),
                ('image', models.ImageField(blank=True, null=True, upload_to='bags/')),
                ('image_hover', models.ImageField(blank=True, null=True, upload_to='bags/')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
            ],
            options={
                'verbose_name': 'Bag',
                'verbose_name_plural': 'Bags',
                'ordering': ['-created_at'],
            },
        ),
    ]
