# Generated by Django 5.2.6 on 2025-10-08 22:31

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('shop', '0028_bag'),
    ]

    operations = [
        migrations.CreateModel(
            name='Shoes',
            fields=[
                ('shoes_product_id', models.AutoField(primary_key=True, serialize=False)),
                ('name', models.CharField(max_length=255)),
                ('price', models.DecimalField(decimal_places=2, max_digits=10)),
                ('collection', models.CharField(blank=True, choices=[('Most_Selling', 'Most Selling'), ('Trending', 'Trending'), ('Sale', 'Sale')], max_length=50, null=True)),
                ('desc', models.TextField(blank=True, null=True)),
                ('image', models.ImageField(blank=True, null=True, upload_to='shoes/')),
                ('image_hover', models.ImageField(blank=True, null=True, upload_to='shoes/hover/')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
            ],
            options={
                'verbose_name': 'Shoe',
                'verbose_name_plural': 'Shoes',
                'ordering': ['-created_at'],
            },
        ),
    ]
