# Generated by Django 5.2.6 on 2025-10-11 23:34

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('shop', '0031_wishlist'),
    ]

    operations = [
        migrations.DeleteModel(
            name='Wishlist',
        ),
    ]
