# Generated by Django 5.2.6 on 2025-10-12 00:19

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('shop', '0032_delete_wishlist'),
    ]

    operations = [
        migrations.CreateModel(
            name='Wishlist',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('customer_id', models.IntegerField()),
                ('category', models.CharField(max_length=50)),
                ('item_product_id', models.IntegerField()),
                ('title', models.CharField(max_length=255)),
                ('price', models.DecimalField(decimal_places=2, default=0, max_digits=10)),
                ('image_url', models.URLField(blank=True, max_length=500, null=True)),
                ('hover_url', models.URLField(blank=True, max_length=500, null=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
            ],
            options={
                'unique_together': {('customer_id', 'item_product_id')},
            },
        ),
    ]
