# Generated by Django 5.2.6 on 2025-10-12 01:58

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('shop', '0033_wishlist'),
    ]

    operations = [
        migrations.AlterUniqueTogether(
            name='wishlist',
            unique_together=set(),
        ),
    ]
